#define IDD_MODE_SELECTION		200
#define IDC_SINGLE_PLAYER		201
#define IDC_MULTIPLAYER			202
#define IDD_DIFFICULTY_SELECTION 203

#define IDC_EASY   1003
#define IDC_MEDIUM 1004
#define IDC_HARD   1005

#define DIFFICULTY_EASY   1
#define DIFFICULTY_MEDIUM 2
#define DIFFICULTY_HARD   3
